name: controlapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.7.2+72
# versinCodguncelle
 

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  xml: ^6.5.0
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.3
  motion_tab_bar: ^2.0.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.6     
  fl_chart: ^0.69.0
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  path_provider: ^2.1.3
  swipe_to: ^1.0.6
  flutter_local_notifications: ^18.0.1
  smooth_page_indicator: ^1.1.0
  easy_loading_button: ^0.3.2
  loading_btn: ^1.0.3
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_email_sender: ^6.0.3
  loading_animation_widget: ^1.2.1
  googleapis_auth: ^1.6.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  http: ^1.2.2
  firebase_remote_config: ^5.1.3
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  flutter_native_splash: ^2.4.2
  package_info_plus: ^8.3.0

  color: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:

    - assets/
    - assets/splash/
    - assets/sound/
    - assets/flags/
    - assets/icons/
    - assets/lottie/
    - assets/social_media/
